import * as vscode from "vscode";
import * as fs from "node:fs";
import * as path from "node:path";
import { renderStepsMarkdown, StepDefExport } from "../exporters/steps-markdown";
import { renderScenariosMarkdown } from "../exporters/scenarios-markdown";
import { ParsedStepDefWithFile } from "../providers/step-resolver";
import { StepUsage, StepUsageIndex } from "../providers/step-usage-index";
import { humanizeRegexSource } from "../providers/pattern-humanizer";
import { toWorkspaceRelative } from "../utils/workspace-path";
import { FeatureParser } from "../parsers/feature-parser";
import { PlaywrightBddExtensionContext } from "../types";

export const OUTSIDE_WORKSPACE_FOLDER = "(outside workspace)";

const ALL_KEYWORDS: Array<"Given" | "When" | "Then"> = ["Given", "When", "Then"];

export function buildBrandLine(version: string, timestamp: string): string {
  return `Generated by Specwright v${version} on ${timestamp}`;
}

function currentBrandLine(): string {
  const pkg = vscode.extensions.getExtension("upscaled-dev.specwright")?.packageJSON as
    | { version?: string }
    | undefined;
  return buildBrandLine(pkg?.version ?? "0.0.0", new Date().toLocaleString());
}

/**
 * Partition items into renderer sections: one anonymous section for single-root
 * (the renderers treat `sections.length > 1` as multi-root), one section per folder,
 * including empty ones, so a multi-root export always renders per-folder headings,
 * plus a trailing "(outside workspace)" bucket so nothing is dropped silently.
 */
export function bucketByFolder<T>(
  items: readonly T[],
  folderNames: readonly string[],
  folderNameOf: (item: T) => string | undefined,
): Array<{ folderName?: string; items: T[] }> {
  if (folderNames.length <= 1) {
    return [{ items: [...items] }];
  }
  const byName = new Map<string, T[]>(folderNames.map((name) => [name, []]));
  const outside: T[] = [];
  for (const item of items) {
    const name = folderNameOf(item);
    const bucket = name === undefined ? undefined : byName.get(name);
    if (bucket) {bucket.push(item);} else {outside.push(item);}
  }
  const sections: Array<{ folderName?: string; items: T[] }> = folderNames.map((name) => ({
    folderName: name,
    items: byName.get(name) ?? [],
  }));
  if (outside.length > 0) {
    sections.push({ folderName: OUTSIDE_WORKSPACE_FOLDER, items: outside });
  }
  return sections;
}

function fanOutKeywords(
  keyword: ParsedStepDefWithFile["keyword"],
): Array<"Given" | "When" | "Then"> {
  return keyword === "Given" || keyword === "When" || keyword === "Then"
    ? [keyword]
    : ALL_KEYWORDS;
}

export function buildStepsSections(
  usages: ReadonlyMap<ParsedStepDefWithFile, StepUsage[]>,
  folderNames: readonly string[],
  folderNameOf: (filePath: string) => string | undefined,
  sourceRelOf: (filePath: string) => string,
): Array<{ folderName?: string; defs: StepDefExport[] }> {
  const buckets = bucketByFolder([...usages.entries()], folderNames, ([def]) =>
    folderNameOf(def.filePath),
  );
  return buckets.map((bucket) => {
    const defs: StepDefExport[] = [];
    for (const [def, uses] of bucket.items) {
      const { label } = humanizeRegexSource(def.pattern, def.isRegex);
      for (const keyword of fanOutKeywords(def.keyword)) {
        defs.push({
          keyword,
          humanized: label,
          verbatim: def.pattern,
          sourceRel: sourceRelOf(def.filePath),
          line: def.line + 1,
          usageCount: uses.length,
        });
      }
    }
    return bucket.folderName === undefined ? { defs } : { folderName: bucket.folderName, defs };
  });
}

export function tagFilterNote(
  tags: readonly string[],
  included: number,
  total: number,
): string {
  return `Filtered by tags ${tags.join(" ")}: ${included} of ${total} features included.`;
}

export function selectedFeaturesNote(included: number, total: number): string {
  return `Selected features: ${included} of ${total} included.`;
}

export function collectKnownTags(
  rawTexts: readonly string[],
  parser: FeatureParser,
): string[] {
  const tags = new Set<string>();
  for (const raw of rawTexts) {
    const parsed = parser.parseFeatureContent(raw);
    for (const scenario of parsed?.scenarios ?? []) {
      for (const tag of scenario.tags ?? []) {tags.add(tag);}
    }
  }
  return [...tags].sort((a, b) => a.localeCompare(b));
}

/** A feature matches when at least one of its scenarios carries any of the chosen tags. */
export function countFeaturesMatchingTags(
  rawTexts: readonly string[],
  tags: readonly string[],
  parser: FeatureParser,
): number {
  const filter = new Set(tags);
  let count = 0;
  for (const raw of rawTexts) {
    const parsed = parser.parseFeatureContent(raw);
    if (!parsed) {continue;}
    if (parsed.scenarios.some((s) => (s.tags ?? []).some((t) => filter.has(t)))) {
      count += 1;
    }
  }
  return count;
}

export async function exportStepsCatalog(
  index: StepUsageIndex,
  collapsed = false,
): Promise<void> {
  const usages = await index.getAllUsages();
  const folderNames = (vscode.workspace.workspaceFolders ?? []).map((f) => f.name);
  const sections = buildStepsSections(
    usages,
    folderNames,
    (filePath) => vscode.workspace.getWorkspaceFolder(vscode.Uri.file(filePath))?.name,
    toWorkspaceRelative,
  );
  const markdown = renderStepsMarkdown(sections, {
    brandLine: currentBrandLine(),
    collapsed,
  });
  await saveAndOpen(markdown, "steps.md");
}

interface FeatureText {
  path: string;
  rawText: string;
}

interface ScenarioSelection {
  features: FeatureText[];
  tagFilter?: string[] | undefined;
  filterNote?: string | undefined;
}

export async function exportScenariosCatalog(
  context: PlaywrightBddExtensionContext,
): Promise<void> {
  const files = await context.discoveryManager.discoverTestFiles();
  if (files.length === 0) {
    vscode.window.showInformationMessage("No feature files found to export.");
    return;
  }

  const scopePick = await vscode.window.showQuickPick(
    [
      { label: "All features", scope: "all" as const },
      { label: "By tag…", scope: "tag" as const },
      { label: "Selected features…", scope: "selected" as const },
    ],
    { placeHolder: "What should the scenario catalog include?" },
  );
  if (!scopePick) {return;}

  const features = await readFeatures(files);
  let selection: ScenarioSelection | undefined;
  if (scopePick.scope === "all") {
    selection = { features };
  } else if (scopePick.scope === "tag") {
    selection = await pickTagScope(features, context.featureParser);
  } else {
    selection = await pickSelectedFeatures(features);
  }
  if (!selection) {return;}

  const folderNames = (vscode.workspace.workspaceFolders ?? []).map((f) => f.name);
  const buckets = bucketByFolder(selection.features, folderNames, (feature) =>
    vscode.workspace.getWorkspaceFolder(vscode.Uri.file(feature.path))?.name,
  );
  const sections = buckets.map((bucket) => {
    const feats = bucket.items.map((f) => ({
      pathRel: toWorkspaceRelative(f.path),
      rawText: f.rawText,
    }));
    return bucket.folderName === undefined
      ? { features: feats }
      : { folderName: bucket.folderName, features: feats };
  });
  const markdown = renderScenariosMarkdown(sections, {
    brandLine: currentBrandLine(),
    tagFilter: selection.tagFilter,
    filterNote: selection.filterNote,
    collapsed: context.config.collapseMarkdownExportSections,
  });
  await saveAndOpen(markdown, "scenarios.md");
}

async function pickTagScope(
  features: FeatureText[],
  parser: FeatureParser,
): Promise<ScenarioSelection | undefined> {
  const rawTexts = features.map((f) => f.rawText);
  const known = collectKnownTags(rawTexts, parser);
  const items = [
    ...known.map((tag) => ({ label: tag, custom: false })),
    { label: "$(edit) Custom tag…", custom: true },
  ];
  const picked = await vscode.window.showQuickPick(items, {
    placeHolder: "Tags to include (a feature matches when any scenario carries any of them)",
    canPickMany: true,
  });
  if (!picked) {return undefined;}

  const tags = picked.filter((p) => !p.custom).map((p) => p.label);
  if (picked.some((p) => p.custom)) {
    const input = await vscode.window.showInputBox({
      prompt: "Custom tags (space-separated, e.g. @smoke @wip)",
    });
    if (input === undefined) {return undefined;}
    for (const token of input.split(/[\s,]+/)) {
      if (token.length > 0) {tags.push(token);}
    }
  }
  if (tags.length === 0) {return undefined;}

  const included = countFeaturesMatchingTags(rawTexts, tags, parser);
  return {
    features,
    tagFilter: tags,
    filterNote: tagFilterNote(tags, included, features.length),
  };
}

async function pickSelectedFeatures(
  features: FeatureText[],
): Promise<ScenarioSelection | undefined> {
  const items = features.map((feature) => ({
    label: path.basename(feature.path),
    description: toWorkspaceRelative(path.dirname(feature.path)),
    feature,
  }));
  const picked = await vscode.window.showQuickPick(items, {
    placeHolder: "Feature files to include",
    canPickMany: true,
  });
  if (!picked || picked.length === 0) {return undefined;}
  return {
    features: picked.map((p) => p.feature),
    filterNote: selectedFeaturesNote(picked.length, features.length),
  };
}

async function readFeatures(files: readonly string[]): Promise<FeatureText[]> {
  const out: FeatureText[] = [];
  for (const file of files) {
    try {
      out.push({ path: file, rawText: await fs.promises.readFile(file, "utf-8") });
    } catch { /* unreadable feature files are skipped */ }
  }
  return out;
}

async function saveAndOpen(markdown: string, defaultName: string): Promise<void> {
  const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  const defaultUri = vscode.Uri.file(root ? path.join(root, defaultName) : defaultName);
  const target = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { Markdown: ["md"] },
  });
  if (!target) {return;}
  await fs.promises.writeFile(target.fsPath, markdown, "utf-8");
  const doc = await vscode.workspace.openTextDocument(target);
  await vscode.window.showTextDocument(doc);
}
