/**
 * The Specwright mark, inlined as a self-contained data URI so an exported catalog
 * carries its own logo with no external asset to ship alongside the .md file. It is the
 * 24×24 activity-bar icon (media/activity-bar-icon.svg) as a base64 PNG.
 *
 * Note: renders in VS Code's Markdown preview and most viewers; GitHub's sanitizer strips
 * `data:` image URIs, so on github.com the heading falls back to the img alt text.
 */
export const SPECWRIGHT_LOGO_DATA_URI =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAGKADAAQAAAABAAAAGAAAAADiNXWtAAAEN0lEQVRIDaWVXWgcVRTHZ3Zm9nuTZvNRSRu6EULVh6qYgrZSRUuRWqGC4kOpqC9+PRjwQTCKFSFSCkKxD0IfJBYUbV8UbOsXWEwfSosP0vZpu5vWrIlturqbZDM7u7Pj70x2ltnpYBEvXO69//PxP+fcc2fUF/bet87OtBpKYGTMrBqAuo5L8bLTBYQcNDOW0VeMRu34sUuWX26a5phhGI/Zth3x495e0zTHsqzvEolE0cPCVoI39DBBs9lMRqP6E5oW2eI4ygw6Zltvvaqq2xzH+SoSiZwJsw1ioQSpVOoiEX6mqspzhhF97y+GGBLxA4aur9d0fZIsloLOws6hBERpNxqNmqo69SVGNputiLFl1ZYpfJPtMjqtMIdBLLTGfqVMJmNQkg1+7L/sQzMQB1ywSp1VTVN0srljdXVVp2QxRXH+tbuC5KEZEPEANd4FQbpardboqKJmGAccR8uBZyB8fWFhIRV0Fna+JYPFxcUNRH+CGi9ZVuvdnp6ev8Xwz/mVN03z+srIyMgNCA8NDQ3tJqtXb9eqXRnQ/5v7+vp+JoOzlUrlmWQyeo5oP4Lw83z+1+rY2Fg9Ho+fLhQK461W63chMk3nzrDIPaxDQCkGdF2fwvDk7OzsZH9/f1WUyKQMYYnL7tReiIh+EnFZ05rPI094DoNrhyAWi+1EmKb/D27M5R4mm92QbqbWh+bm5ibHx8e7PicQRMjsWwLYRiePiGOI+nmk+8j6UfZuQO4dFIvFOJe3HfAH0j7IY3rc4RlDWksmk5fJ6nsI8+KEi9/E3MG8F/3jzDJle4T1Gs4n8PMaarV6vf4i6wWXIJcbXGfbyjDgNzj8EAEtuVYRDEaZT4LJx00emaxRpoy7yWKe9R4yn4hGo1I2Mcxic4B1T7uLUjymppQLv23PHHyDAJ1rODvPuorxVtTuQh4nu8usW3H+BqsbFTrz4IfF3iWg1it8f6TfUwiukn5XZ2BQI/0ZHD+E4wz7U+jcxH4ZbCPN8azP+VXkH0B4AqzXvWR6vYJhHqPtCI8i6BoQmMgaQozeIA6fBrtOMFyV/grKPWIAVhLnvKUv0JNSKi4BBxvlH4lmJ93xJaW4IEJvIJdSiI570ZwzkDwlkVPQAdFrZ/k+VZgeHh6uebYugRxQPovjn9Lp9DGieAeDGWBXEYcp5LvAz4HPij5DGsFY2yoVy2q+RVmOgkkjdEaHAEGL6KdYC2TyMs6mMToM6dc4/QWLK5QoT7d8zLngeWD/B33/djwePeJh/rXdRWsQd3GTT8QErfoSzvaC3oDgN6b7RwNL6LpxP+08zRvZhzxJIFOlUulTv1P/votABL29vfJpOEKkJ8lmB/NBvtqD/DptibbVap5GdgpcLjJGWa6Mjo56v1S/b3d/C4GgGIqB9LfMT5hhoxwGBjG9T4kn9u/f4l1WUP6/znozFvsHZiATf8N7bfoAAAAASUVORK5CYII=";

export interface MastheadOptions {
  brandLine?: string | undefined;
  /** Headline counts (e.g. "3 features", "12 scenarios") joined into the caption. */
  stats?: string[] | undefined;
}

/**
 * Masthead shared by both catalog exports: the logo inlined in the H1, an optional
 * caption line in small text (the "generated by" brand line plus headline counts), and a
 * horizontal rule separating it from the body. Returned as a block (no trailing blank) so
 * callers can `pushBlock` the rest after it.
 */
export function renderMasthead(title: string, options?: MastheadOptions): string[] {
  const lines = [
    `# <img src="${SPECWRIGHT_LOGO_DATA_URI}" width="24" height="24" alt="Specwright" /> ${title}`,
  ];
  const caption = [options?.brandLine, ...(options?.stats ?? [])]
    .filter((part): part is string => Boolean(part))
    .join(" · ");
  if (caption) {
    lines.push("", `<sub>${caption}</sub>`);
  }
  lines.push("", "---");
  return lines;
}

/** Thin closing footer mirroring the masthead: a rule and a small "Specwright · …" caption. */
export function renderFooter(stats: string[]): string[] {
  const caption = ["Specwright", ...stats].join(" · ");
  return ["---", "", `<sub>${caption}</sub>`];
}

/**
 * Opening tag for a collapsible section: `<details open>` normally, or `<details>` when the
 * export is configured to start collapsed (better for large catalogs).
 */
export function detailsTag(collapsed?: boolean): string {
  return collapsed ? "<details>" : "<details open>";
}

/** English pluralization for a count + noun, e.g. `countLabel(1, "feature")` → "1 feature". */
export function countLabel(count: number, singular: string, plural = `${singular}s`): string {
  return `${count} ${count === 1 ? singular : plural}`;
}
