import { describe, it, expect } from "vitest";
import {
  bucketByFolder,
  buildBrandLine,
  buildStepsSections,
  collectKnownTags,
  countFeaturesMatchingTags,
  selectedFeaturesNote,
  tagFilterNote,
  OUTSIDE_WORKSPACE_FOLDER,
} from "../../commands/export-catalogs";
import { FeatureParser } from "../../parsers/feature-parser";
import type { ParsedStepDefWithFile } from "../../providers/step-resolver";
import type { StepUsage } from "../../providers/step-usage-index";

function def(
  pattern: string,
  opts: {
    keyword?: "Given" | "When" | "Then" | "Step" | undefined;
    isRegex?: boolean;
    filePath?: string;
    line?: number;
  } = {}
): ParsedStepDefWithFile {
  return {
    line: opts.line ?? 0,
    regex: /x/,
    pattern,
    isRegex: opts.isRegex ?? false,
    keyword: opts.keyword,
    filePath: opts.filePath ?? "/ws/app/steps/a.steps.ts",
  };
}

function usageMap(
  entries: Array<[ParsedStepDefWithFile, number]>
): Map<ParsedStepDefWithFile, StepUsage[]> {
  return new Map(
    entries.map(([d, count]) => [
      d,
      Array.from({ length: count }, (_, i) => ({
        featurePath: "/ws/app/f.feature",
        line: i,
        stepText: "x",
        keyword: "Given" as const,
      })),
    ])
  );
}

const identity = (fp: string): string => fp;

describe("buildStepsSections", () => {
  it("fans out Step and keyword-less definitions into all three keywords", () => {
    const sections = buildStepsSections(
      usageMap([
        [def("shared", { keyword: "Step" }), 2],
        [def("no keyword", { line: 1 }), 0],
        [def("only when", { keyword: "When", line: 2 }), 1],
      ]),
      [],
      () => undefined,
      identity
    );

    expect(sections).toHaveLength(1);
    const byKeyword = (kw: string): string[] =>
      sections[0]!.defs.filter((d) => d.keyword === kw).map((d) => d.humanized);
    expect(byKeyword("Given")).toEqual(["shared", "no keyword"]);
    expect(byKeyword("When")).toEqual(["shared", "no keyword", "only when"]);
    expect(byKeyword("Then")).toEqual(["shared", "no keyword"]);
  });

  it("maps humanized/verbatim, 1-based lines, relative source, and usage counts", () => {
    const sections = buildStepsSections(
      usageMap([
        [
          def("^the count is (\\d+)$", {
            keyword: "Then",
            isRegex: true,
            filePath: "/ws/app/steps/count.steps.ts",
            line: 4,
          }),
          3,
        ],
      ]),
      [],
      () => undefined,
      (fp) => fp.replace("/ws/app/", "")
    );

    expect(sections[0]!.defs).toEqual([
      {
        keyword: "Then",
        humanized: "the count is {int}",
        verbatim: "^the count is (\\d+)$",
        sourceRel: "steps/count.steps.ts",
        line: 5,
        usageCount: 3,
      },
    ]);
  });

  it("returns a single anonymous section for a single workspace folder", () => {
    const sections = buildStepsSections(
      usageMap([[def("a", { keyword: "Given" }), 0]]),
      ["app"],
      () => "app",
      identity
    );
    expect(sections).toHaveLength(1);
    expect(sections[0]!.folderName).toBeUndefined();
  });

  it("multi-root: sections per folder plus an outside-workspace fallback bucket", () => {
    const inApp = def("in app", { keyword: "Given", filePath: "/ws/app/s.ts" });
    const stray = def("stray", { keyword: "Given", filePath: "/elsewhere/s.ts", line: 1 });
    const sections = buildStepsSections(
      usageMap([
        [inApp, 1],
        [stray, 0],
      ]),
      ["app", "lib"],
      (fp) => (fp.startsWith("/ws/app/") ? "app" : undefined),
      identity
    );

    expect(sections.map((s) => s.folderName)).toEqual(["app", "lib", OUTSIDE_WORKSPACE_FOLDER]);
    expect(sections[0]!.defs.map((d) => d.humanized)).toEqual(["in app"]);
    expect(sections[1]!.defs).toEqual([]);
    expect(sections[2]!.defs.map((d) => d.humanized)).toEqual(["stray"]);
  });
});

describe("bucketByFolder", () => {
  it("keeps a single anonymous bucket when there are no or one workspace folders", () => {
    expect(bucketByFolder([1, 2], [], () => undefined)).toEqual([{ items: [1, 2] }]);
    expect(bucketByFolder([1], ["only"], () => "only")).toEqual([{ items: [1] }]);
  });
});

describe("brand line and filter notes", () => {
  it("formats the brand line as 'Generated by Specwright v<version> on <timestamp>'", () => {
    expect(buildBrandLine("0.2.3", "7/18/2026, 09:15:00")).toBe(
      "Generated by Specwright v0.2.3 on 7/18/2026, 09:15:00"
    );
  });

  it("formats the tag filter note with the inclusion ratio", () => {
    expect(tagFilterNote(["@smoke"], 4, 12)).toBe(
      "Filtered by tags @smoke: 4 of 12 features included."
    );
    expect(tagFilterNote(["@smoke", "@wip"], 1, 2)).toBe(
      "Filtered by tags @smoke @wip: 1 of 2 features included."
    );
  });

  it("formats the selected-features note", () => {
    expect(selectedFeaturesNote(3, 12)).toBe("Selected features: 3 of 12 included.");
  });
});

const SMOKE_FEATURE = [
  "Feature: Checkout",
  "",
  "  @smoke",
  "  Scenario: Pay",
  "    Given a cart",
].join("\n");

const PLAIN_FEATURE = [
  "Feature: Profile",
  "",
  "  Scenario: View",
  "    Given a user",
].join("\n");

const TAGGED_OUTLINE_FEATURE = [
  "Feature: Login",
  "",
  "  @wip",
  "  Scenario Outline: Sign in",
  "    Given I am <user>",
  "",
  "    Examples:",
  "      | user  |",
  "      | admin |",
].join("\n");

describe("tag collection and ratio math", () => {
  const parser = FeatureParser.create();

  it("collects unique known tags sorted alphabetically", () => {
    expect(
      collectKnownTags([SMOKE_FEATURE, PLAIN_FEATURE, TAGGED_OUTLINE_FEATURE], parser)
    ).toEqual(["@smoke", "@wip"]);
  });

  it("counts a feature when any scenario carries any of the chosen tags", () => {
    const raws = [SMOKE_FEATURE, PLAIN_FEATURE, TAGGED_OUTLINE_FEATURE];
    expect(countFeaturesMatchingTags(raws, ["@smoke"], parser)).toBe(1);
    expect(countFeaturesMatchingTags(raws, ["@smoke", "@wip"], parser)).toBe(2);
    expect(countFeaturesMatchingTags(raws, ["@nope"], parser)).toBe(0);
  });

  it("never counts an unparsable feature", () => {
    expect(countFeaturesMatchingTags(["not gherkin at all"], ["@smoke"], parser)).toBe(0);
  });
});
